export const MOCK_SUPPLIERS = [
  { id: "sup-acme", name: "Acme Electrical Components GmbH", code: "ACME-ELEC", contactEmail: "engineering@acme-electro.de", qualityScore: 89.5, trustLevel: "VERIFIED", skuCount: 12, avgCompleteness: 92.4 },
  { id: "sup-apex", name: "Apex Sensor & Precision Systems LLC", code: "APEX-SENS", contactEmail: "support@apex-sensors.com", qualityScore: 63.0, trustLevel: "PROBATION", skuCount: 8, avgCompleteness: 74.1 },
  { id: "sup-nordic", name: "Nordic Automation & Drives AB", code: "NORDIC-AUTO", contactEmail: "catalog@nordic-automation.se", qualityScore: 94.0, trustLevel: "VERIFIED", skuCount: 7, avgCompleteness: 95.8 },
  { id: "sup-rhine", name: "Rhine Industrial Dynamics AG", code: "RHINE-IND", contactEmail: "inbound@rhine-dynamics.ch", qualityScore: 72.0, trustLevel: "STANDARD", skuCount: 5, avgCompleteness: 81.0 },
];

export const MOCK_PRODUCTS = [
  {
    id: "prod-sch-c60h-16a",
    sku: "SCH-C60H-2P-16A",
    gtin: "3606480439819",
    title: "Acti9 C60H Circuit Breaker 2P 16A 10kA C-Curve",
    description: "Miniature circuit breaker for electrical distribution and motor protection in industrial switchboards.",
    brand: "Schneider Electric",
    price: 42.50,
    currency: "USD",
    category: "Circuit Breakers",
    taxonomyCode: "EC000042",
    status: "PUBLISHED",
    completenessScore: 96.5,
    agentVisibilityScore: 98.0,
    agentVisibilityTier: "TRUSTED",
    acpFillRate: 97.5,
    ucpFillRate: 98.5,
    supplierId: "sup-acme",
    supplier: MOCK_SUPPLIERS[0],
    validationIssues: [],
    attributes: JSON.stringify({ rated_voltage: "400V AC", current_rating: "16A", poles: "2P", breaking_capacity: "10kA", curve: "C", protection_ip: "IP20" }),
    highlights: JSON.stringify(["10kA breaking capacity according to EN 60898-1", "VisiSafe technology guarantees safe downstream maintenance", "IP20 finger-safe terminal isolation"]),
    qaPairs: JSON.stringify([
      { question: "What is the breaking capacity of this breaker?", answer: "10kA at 400V AC according to IEC/EN 60898-1." },
      { question: "Is this suitable for inductive motor loads?", answer: "Yes, the C-curve magnetic trip (5-10 In) accommodates motor inrush currents." }
    ]),
  },
  {
    id: "prod-pho-quint4-5a",
    sku: "PHO-QUINT4-24DC-5A",
    gtin: "4046356985413",
    title: "QUINT4 Switched Power Supply 24V DC 5A Primary Switch",
    description: "Primary-switched QUINT POWER supply unit with SFB (Selective Fuse Breaking) technology and preventive function monitoring.",
    brand: "Phoenix Contact",
    price: 195.00,
    currency: "USD",
    category: "Power Supplies",
    taxonomyCode: "EC002540",
    status: "APPROVED",
    completenessScore: 94.0,
    agentVisibilityScore: 96.0,
    agentVisibilityTier: "TRUSTED",
    acpFillRate: 95.0,
    ucpFillRate: 97.0,
    supplierId: "sup-acme",
    supplier: MOCK_SUPPLIERS[0],
    validationIssues: [],
    attributes: JSON.stringify({ input_voltage: "100-240V AC", output_voltage: "24V DC", output_current: "5A", efficiency: "92.5%", protection_ip: "IP20" }),
  },
  {
    id: "prod-sck-w16-sensor",
    sku: "SCK-W16-IO-LINK",
    gtin: "4047084439056",
    title: "W16 Photoelectric Sensor LineSpot IO-Link IP67",
    description: "High-precision photoelectric proximity sensor featuring LineSpot optical technology and dual digital IO-Link output.",
    brand: "SICK",
    price: 185.00,
    currency: "USD",
    category: "Sensors",
    taxonomyCode: "EC002717",
    status: "REVIEW",
    completenessScore: 81.2,
    agentVisibilityScore: 84.0,
    agentVisibilityTier: "PENALIZED",
    acpFillRate: 82.0,
    ucpFillRate: 86.0,
    supplierId: "sup-apex",
    supplier: MOCK_SUPPLIERS[1],
    validationIssues: [{ id: "iss-1", severity: "WARNING", type: "MISSING", message: "Missing IP rating washdown certificate for outdoor enclosure", resolved: false }],
    attributes: JSON.stringify({ sensing_range: "100-800mm", light_source: "PinPoint LED", output_type: "IO-Link / PNP", supply_voltage: "10-30V DC" }),
  },
  {
    id: "prod-dan-vlt-fc302",
    sku: "DAN-VLT-FC302-3KW",
    gtin: "5702427891340",
    title: "Danfoss VLT AutomationDrive 3.0 kW 380-480V IP20",
    description: "Heavy-duty variable frequency drive designed for synchronous and induction motor control in industrial processing plants.",
    brand: "Danfoss Drives",
    price: 680.00,
    currency: "USD",
    category: "VFDs",
    taxonomyCode: "EC001857",
    status: "PUBLISHED",
    completenessScore: 98.0,
    agentVisibilityScore: 99.0,
    agentVisibilityTier: "TRUSTED",
    acpFillRate: 98.5,
    ucpFillRate: 99.5,
    supplierId: "sup-nordic",
    supplier: MOCK_SUPPLIERS[2],
    validationIssues: [],
    attributes: JSON.stringify({ power_rating: "3.0 kW", supply_voltage: "380-480V 3PH", output_current: "7.2A", enclosure: "IP20", fieldbus: "PROFINET / Modbus TCP" }),
  },
  {
    id: "prod-wag-221-415",
    sku: "WAG-221-415-LEVER",
    gtin: "4050821808466",
    title: "WAGO 221 Splicing Connector 5-Wire Lever-Nut 32A",
    description: "Compact 5-wire connector for solid, stranded and fine-stranded conductors up to 4mm² with clear transparent housing.",
    brand: "WAGO",
    price: 1.20,
    currency: "USD",
    category: "Terminal Blocks",
    taxonomyCode: "EC000447",
    status: "PUBLISHED",
    completenessScore: 99.0,
    agentVisibilityScore: 100.0,
    agentVisibilityTier: "TRUSTED",
    acpFillRate: 100.0,
    ucpFillRate: 100.0,
    supplierId: "sup-rhine",
    supplier: MOCK_SUPPLIERS[3],
    validationIssues: [],
    attributes: JSON.stringify({ wire_gauge: "0.2-4 mm²", rated_current: "32A", rated_voltage: "450V", positions: "5-Wire", mounting: "Free-hanging" }),
  },
];

export const MOCK_FEEDS = [
  {
    id: "feed-acp-1",
    protocol: "ACP",
    name: "OpenAI / Stripe Agentic Commerce Feed (Global Catalog)",
    itemsCount: 32,
    fillRatePercent: 94.5,
    lastPushedAt: new Date().toISOString(),
    deliveryJobs: [
      { id: "job-1", status: "SUCCESS", httpStatus: 200, startedAt: new Date().toISOString(), triggeredBy: "Workspace Admin" }
    ],
  },
  {
    id: "feed-ucp-1",
    protocol: "UCP",
    name: "Google Universal Commerce Protocol Feed (Enterprise Registry)",
    itemsCount: 32,
    fillRatePercent: 96.2,
    lastPushedAt: new Date().toISOString(),
    deliveryJobs: [
      { id: "job-2", status: "SUCCESS", httpStatus: 200, startedAt: new Date().toISOString(), triggeredBy: "Workspace Admin" }
    ],
  },
];

export const MOCK_ANALYTICS = {
  metrics: {
    totalSkus: 32,
    avgCompletenessScore: 92.4,
    avgAgentVisibilityScore: 95.1,
    avgAcpFillRate: 94.5,
    avgUcpFillRate: 96.2,
    unresolvedIssuesCount: 3,
  },
  statusDistribution: {
    draft: 4,
    enriching: 2,
    review: 6,
    approved: 8,
    published: 12,
  },
  visibilityTiers: {
    trusted: 24,
    penalized: 6,
    invisible: 2,
  },
  issuesBySeverity: { CRITICAL: 0, ERROR: 1, WARNING: 2, INFO: 0 },
  issuesByType: { MISSING: 2, ANOMALY: 1, CROSS_FIELD: 0, MISMATCH: 0 },
  categoryDistribution: {
    "Circuit Breakers": 8,
    "Power Supplies": 6,
    "Sensors": 6,
    "VFDs": 5,
    "Terminal Blocks": 4,
    "PLCs & Controllers": 3,
  },
  supplierLeaderboard: MOCK_SUPPLIERS,
  recentIssues: [
    { id: "iss-1", severity: "WARNING", type: "MISSING", message: "Missing IP rating washdown certificate for outdoor enclosure", product: { sku: "SCK-W16-IO-LINK", title: "W16 Photoelectric Sensor", category: "Sensors" } }
  ],
};
